### ISSUE TITLE
BatchClientImpl Blocks if Calls Reordered

### ISSUE THREAD

**Issue by tslilyai** [Microsoft/EmbeddedSocial-Java-API-Library#17]
If `issueBatch()` is called prior to the interceptor being invoked on a request (e.g., a call to `createTopicAsync()`) then the batch client will be blocked. This occurs because `issueBatch()` will block on the `latch.await()` invocation, which is only decremented by when the interceptor is invoked. I believe this is happening because the same object (the same `BatchClientImpl` instance) is waiting and also intercepting requests.

A failing example:
```java
EmbeddedSocialBatchedClientImpl batchOps = new EmbeddedSocialBatchedClientImpl.Builder()
                .batchSize(k)
                .baseUrl(ESClient.baseURL)
                .build();
try {
   // the batchOps thread blocks here
   batchOps.issueBatch();
} catch (InterruptedException | IOException e) {
    System.out.println(e.getMessage());
}
for (int i = 0; i < k; i++) {
    // the interceptor gets invoked here
     batchOps.getEsClient().getBuildsOperations().getBuildsCurrentAsync(callback);
}
```

**Comment by ssaroiu** [comment]
This behavior is by design. issueBatch will block until all requests are intercepted. While issueBatch is blocked, the BatchClientImpl remains active intercepting further requests. This behavior was tested in different ways and appears to work correctly.

In the example above, the code blocks on batchOps.issueBatch() and never reaches the for-loop below. I'm not sure exactly what the code's intent is, however, you could consider calling issueBatch on a separate thread that will remain blocked until the batch is complete.

This StackOverflow article illustrates how to make a call (e.g., issueBatch) on a separate thread.
